version: 29
jobs:
- name: sync
  steps:
  - !PullRepository
    name: pull
    remoteUrl: https://github.com/univrs-cloud/portainer.git
    syncToChildProject: false
    passwordSecret: GitHub
    refs: refs/heads/* refs/tags/*
    withLfs: false
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PushRepository
    name: push
    remoteUrl: https://github.com/univrs-cloud/portainer.git
    passwordSecret: GitHub
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !ScheduleTrigger
    cronExpression: 0 0 1 * * ?
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
